			<ul class="breadcrumb">
				<li>
					<i class="icon-home"></i>
					<a href="/">Home</a> 
					<i class="icon-angle-right"></i>
				</li>
				<li><a href="#">内容列表</a></li>
			</ul>

			<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="halflings-icon align-justify"></i><span class="break"></span>内容列表</h2>
						<div class="box-icon">
							<a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
							<a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
							<a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
						</div>
					</div>
					<div class="box-content">
						<div class="row-fluid">
							<div class="">
								<div class="" id="">
									<label></label>
									<form name="form1" action="/message/list" method="post">
									标题: <input type="text" name="title" id="title" value="<?php echo isset($where['title'])?$where['title']:'';?>">
									状态：
                                                                        <select name="status" id="status" style="width:auto;">
                                                                                <option value="">全部</option>
                                                                                <option value="Sent" <?php echo (isset($where['status']) && $where['status']=='Sent'?'selected="selected"':'');?>>Sent</option>
                                                                                <option value="New" <?php echo (isset($where['status']) && $where['status']=='New'?'selected="selected"':'');?>>New</option>
                                                                                <option value="Drafts" <?php echo (isset($where['status']) && $where['status']=='Drafts'?'selected="selected"':'');?>>Drafts</option>
                                                                                <option value="Trash" <?php echo (isset($where['status']) && $where['status']=='Trash'?'selected="selected"':'');?>>Trash</option>
                                                                        </select>
									开始时间：<input type="text" name="bctime" id="bctime" value="<?php echo isset($where['bctime'])?$where['bctime']:'';?>" style="width:80px;" onclick="WdatePicker({maxDate:'#F{$dp.$D(\'ectime\')}'})" />
									结束时间：<input type="text" name="ectime" id="ectime" value="<?php echo isset($where['ectime'])?$where['ectime']:'';?>" style="width:80px;" onclick="WdatePicker({minDate:'#F{$dp.$D(\'bctime\')}'})" />
									<input id="submit" type="submit" value="查询" class="btn btn-primary btn-search" />
									<!--<input id="btnAdd" type="button" value="添加内容" class="btn btn-primary btn-search" />-->
									</form>
								</div>
							</div>
						</div>
						<table class="table table-striped table-bordered bootstrap-datatable datatable">
						  <thead>
							  <tr>
							  	  <!--<th width="10"><input type="checkbox" name="ckall" /></th>-->
								  <th>标题</th>
								  <th>类型</th>
                                                                  <th>状态</th>
								  <th>添加时间</th>
								  <th>操作</th>
							  </tr>
						  </thead>   
						  <tbody>
						  <?php foreach ($page->items as $item):?>
							<tr>
								<!--<td><input type="checkbox" name="id" value="<?php echo $item->id;?>" /></td>-->
								<td><?php echo $item->title;?></td>
								<td class="center"><?php echo $item->type;?></td>
								<td><?php echo $item->status;?></td>
								<td><?php echo $item->ctime;?></td>
								<td class="center">
									<!--a class="btn btn-success" href="#">
										<i class="halflings-icon white zoom-in"></i>  
									</a-->
									<a title="编辑内容" class="btn btn-info" href="/message/edit/<?php echo $item->id;?>">
										<i class="halflings-icon white edit"></i>  
									</a>
									<!--a class="btn btn-danger" href="#">
										<i class="halflings-icon white trash"></i> 
									</a-->
								</td>
							</tr>
							<?php endforeach;?>
						</tbody>
					  </table> 
					  <div class="row-fluid">
						  <div class="span12 center">
							  <div class="dataTables_paginate paging_bootstrap pagination">
						  	  	  <span class="page_text">共有 <?php echo $page->total_items;?> 条记录, 每页显示 <?php echo $page->pageSize;?> 条, 当前<?php echo $page->current;?>/<?php echo ($page->total_pages==0?1:$page->total_pages);?> 页:</span>
								  <ul>
								  	  <li class="prev"><a href="/message/list">首页</a></li>
									  <li class="prev"><a href="/message/list/<?php echo $page->before;?>/<?php echo $page->pageSize;?>">上一页</a></li>
									  <li class="next"><a href="/message/list/<?php echo $page->next;?>/<?php echo $page->pageSize;?>">下一页</a></li>
									  <li class=""><a href="/message/list/<?php echo $page->last;?>/<?php echo $page->pageSize;?>">尾页</a></li>
								  </ul>
								  <span class="page_text">每页行数:</span>
								  <select name="pagesize" style="width:auto;" class="pagesize" onchange="location.href='/message/list/1/'+this.value;">
									<option value="10"<?php if($page->pageSize==10):?> selected="selected"<?php endif;?>>10</option>
									<option value="25"<?php if($page->pageSize==25):?> selected="selected"<?php endif;?>>25</option>
									<option value="50"<?php if($page->pageSize==50):?> selected="selected"<?php endif;?>>50</option>
									<option value="100"<?php if($page->pageSize==100):?> selected="selected"<?php endif;?>>100</option>
								</select> 
								<span class="page_text"> 条</span>
							  </div>
						  </div>
					  </div>           
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
