			<ul class="breadcrumb">
				<li>
					<i class="icon-home"></i>
					<a href="/">Home</a> 
					<i class="icon-angle-right"></i>
				</li>
				<li><a href="#">模板管理</a><i class="icon-angle-right"></i></li>
				<li><a href="#">模板列表</a></li>
				<li>
			</ul>

			<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="halflings-icon align-justify"></i><span class="break"></span>模板列表</h2>
						<div class="box-icon">
							<a href="/template/edit">新增模板</a>
							<a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
							<a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
						</div>
					</div>
					<div class="box-content">
						<div class="row-fluid">
							 
							<div class="span12">
							<?php echo \Phalcon\Tag::form(array("/template/list", "method" => "post",'class'=>'form-horizontal')); ?>
								<div class="dataTables_filter">
                                	名字：<?php echo \Phalcon\Tag::textField(array("name", "class" => "span2 typeahead" , "value"=>isset($where['name']) ? $where['name'] : '')) ?>
                                	状态：<?php echo \Phalcon\Tag::selectStatic(array("status", array(''=>'全部','Enabled' => '启用', 'Disabled' => '未启用'),'class'=>'span2',"value"=>isset($where['status']) ? $where['status'] : ''));?>
                                	类型：<?php echo \Phalcon\Tag::selectStatic(array("type", array(''=>'全部','SMS' => 'SMS', 'Email' => 'Email'),'class'=>'span2',"value"=>isset($where['type']) ? $where['type'] : ''));?>
                                	<?php echo \Phalcon\Tag::submitButton(array("查询",'class'=>'btn btn-small btn-primary')) ?>
								</div>
							<?php echo \Phalcon\Tag::endForm()?>
							</div>
						</div>
						<table class="table table-striped table-bordered bootstrap-datatable datatable">
						  <thead>
							  <tr>
								  <th width="1%">ID</th>
								  <th width="6%">模板名字</th>
								  <th width="9%">模板描述</th>
								  <th width="3%">模板类型</th><!--  <th width="2%">模板引擎</th>-->
								  <th width="4%">创建时间</th>
								  <th width="4%">修改时间</th>
								  <th width="1%">状态</th>
								  <th width="4%">操作</th>
							  </tr>
						  </thead>   
						  <tbody>
						  <?php foreach ($page->items as $item):?>
						  
							<tr>
								<td><?php echo $item->id;?></td>
							
								<td><?php echo $item->name;?></td>
								<td><?php echo $item->decription;?></td>
								
								<td><?php echo isset($type_name[$item->type]) ? $type_name[$item->type] : $item->type;?></td><!--  <td><?php echo $item->engine;?></td>-->
								<td><?php echo $item->ctime;?></td>
								<td><?php echo $item->mtime;?></td>
								<td class="center">
								<?php if($item->status=='Enabled') :?>
								<span class="label label-success">启用</span>
								<?php else :?>
								<span class="label label-error">未启用</span>
								<?php endif ;?>
								</td>
								<td class="center">
									
									<a title="编辑" class="btn btn-info" href="/template/edit/<?php echo $item->id ?>">
										<i class="halflings-icon white edit"></i>  
									</a>
									 
									<a title="删除" class="btn btn-danger"  href="/template/delete/<?php echo $item->id ?>" onclick='if(!confirm("确定要删除该数据吗？")){return false;}'>
										<i class="halflings-icon white trash"></i> 
									</a>
									
								</td>
							</tr>
							<?php endforeach;?>
							
						</tbody>
					  </table> 
					  <div class="form-actions hide">
							全选<?php echo \Phalcon\Tag::checkField(array("", "size" => 10 ,'id'=>'selectAll')) ?>:
							  <?php echo \Phalcon\Tag::submitButton(array("启用",'class'=>'btn  btn-small btn-primary submit_status','data-post'=>'{"status":"Enabled"}')) ?>
							  <?php echo \Phalcon\Tag::submitButton(array("关闭",'class'=>'btn  btn-small btn-primary submit_status','data-post'=>'{"status":"Disabled"}')) ?>
						</div>
					  <div class="row-fluid">
						  <div class="span12 center">
							  <div class="dataTables_paginate paging_bootstrap pagination">
						  	  	  <span class="page_text">共有 <?php echo $page->total_items;?> 条记录, 每页显示 <?php echo $page->pageSize;?> 条, 当前<?php echo $page->current;?>/<?php echo $page->total_pages;?> 页:</span>
								  <ul> 
								  	  <li class="prev"><a href="/template/list">首页</a></li>
									  <li class="prev"><a href="/template/list/<?php echo $page->before;?>/<?php echo $page->pageSize;?>">← 上一页</a></li>
									  <li class="next"><a href="/template/list/<?php echo $page->next;?>/<?php echo $page->pageSize;?>">下一页 → </a></li>
									  <li class=""><a href="/template/list/<?php echo $page->last;?>/<?php echo $page->pageSize;?>">尾页</a></li>
								  </ul>
								  
								  
								<?php echo \Phalcon\Tag::selectStatic(array("pagesize", array('10'=>'10','25' => '25', '50' => '50','100'=>'100'),'class'=>'span1',"value"=>$page->pageSize , "onchange"=>"location.href='/template/list/1/'+this.value;"));?>
								
								
							  </div>
						  </div>
					  </div>
					  
					  
					           
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
			<script>
			$(document).ready(function(){
				$('#selectAll').click(function(){
					var checked = $(this).is(':checked');
					$('.selected_id').attr("checked",checked);
					var div_checked = $('.selected_id').parent('span');
					if(checked){
						div_checked.addClass('checked');
					}else{
						div_checked.removeClass('checked');
					}
				});
				$('#submit_status').click(function(){
					$.ajax({
				        type: "POST",
				        url: '/template/listpost',
				        data: {'ajax':1},
				        async:false,
				        dataType: "json",
				        success: function(data){
				        	$('#myModal>.modal-body>p').html(data.msg);
				        	$('#myModal').modal('show');
				        	loadtable();
				    	}
				    });
					return false;
				})
			});
			</script>
