<script type="text/javascript">


</script>
<div class="row-fluid sortable">		
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon user"></i><span class="break"></span><?php ?></h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
            </div>
        </div>
        
        <div class="box-content">
            <div class="row-fluid">
							<div class="">
								<div class="" id="" style="float:left">
									<label></label>
									<form name="form1" action="/category/list" method="post">
									
									语言：
									<select name="language" id="language" style="width:auto;">
										<option value="">全部</option>
										<?php foreach($language as $k => $v):?>
										<option value="<?php echo $k;?>"<?php if(isset($where['language']) && $where['language']==$k):?> selected="selected"<?php endif;?>><?php echo $v;?></option>
										<?php endforeach;?>
									</select>
									
									<!--<input id="submit" type="submit" value="查询" class="btn btn-primary btn-search" />-->
									</form>
								</div>
                                                            <div style="float:right"><a href="/category/add"><input  type="button" value="添加分类" class="btn btn-primary btn-search" /></a></div>
							</div>
						</div>
            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr>
                        
                        <th>分类名称</th>
                        <th>层级</th>
                        <th>分类描述</th>
                        <th>语言</th>
                        <th>可见性</th>
                        <th>类型</th>
                        <th>创建时间</th>
                        <th>修改时间</th>
                        <th>操作</th>
                    </tr>
                </thead>   
                <tbody>
                    <?php
                    $cates_arr = $this->objToArray->ohYeah($pages);
                    $items = $this->tree->_tree($cates_arr, $parent_id = 0, $level = 0);
                    foreach ($items as $vs) {
                        ?>
                        <tr language="<?php echo $vs['language'];?>">
                            
                            <td>
                                <?php echo str_repeat("&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;", $vs['level']); ?>
    <?php echo $vs['name']; ?>
                            </td>
                            <td ><?php echo $vs['level']+1?></td>
                            <td><?php echo $vs['description']; ?></td>
                            <td><?php if($vs['language'] == 'cn'){
                                                                        echo '简体';
                                                                    }elseif($vs['language'] == 'tw'){
                                                                        echo '繁体';
                                                                    }else{
                                                                        echo '英语';
                                                                    }?></td>
                            <td class="center">
                                <?php echo $vs['visibility']=='Visible'?'<span class="label label-success">显示</span>':'<span class="label label-error">隐藏</span>';?>
                            </td>
                            <td><?php echo $vs['type']; ?></td>
                            <td><?php echo $vs['ctime']; ?></td>
                            <td><?php echo $vs['mtime']; ?></td>
                            <td class="center">
                                <a title="查看分类" class="btn btn-success" href="/category/show/<?php echo $vs['id'];?>">
                                    <i class="halflings-icon white zoom-in"></i>  
                                </a>
                                <a title="编辑分类" class="btn btn-info" href="/category/edit/<?php echo $vs['id'];?>">
                                    <i class="halflings-icon white edit"></i>  
                                </a>
                                <a title="添加分类" class="btn btn-success" href="/category/add/<?php echo $vs['id'];?>">
                                    <i class="halflings-icon plus white zoom-in"></i>  
                                </a>
                               
                            </td>
                        </tr>
<?php } ?>

                </tbody>
            </table>   
            
        </div>
    </div><!--/span-->

</div><!--/row-->
<script language="javascript" type="text/javascript">
    $(function(){
        $("#language").change(function(){
            var language = $(this).children('option:selected').val();
            $('.datatable tbody tr').hide();
            $('.datatable tbody tr[language="'+language+'"]').show();
//            $.post('index',{language:language},function(data){
//                if(!data.status){
//            },'json');
        });

      });
</script>





