<?php $cates_arr = $this->objToArray->ohYeah(Category::find('site_id='.$site_id));
			$items = $this->tree->_tree($cates_arr, $parent_id = 0, $level = 0); 
?><ul class="breadcrumb">
				<li>
					<i class="icon-home"></i>
					<a href="/">Home</a> 
					<i class="icon-angle-right"></i>
				</li>
				<li><a href="#">模板管理</a><i class="icon-angle-right"></i></li>
				<li><a href="#">分类模板关联</a></li>
			</ul>

			<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="halflings-icon align-justify"></i><span class="break"></span>分类模板关联</h2>
						<div class="box-icon">
							<a href="/category/index">分类列表</a>
							<a href="/template/index">模板列表</a>
							<a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
							<a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
						</div>
					</div>
					<div class="box-content">
					<?php echo \Phalcon\Tag::form(array("", "method" => "post",'class'=>'form-horizontal')); ?>
						 <fieldset>
								
								<div class="control-group">
								<label class="control-label" for=template_id>分类</label>
								<div class="controls">
								<select name="category_id" id="category_id">
								<option value="">请选择</option>
							  <?php 
                                    foreach ($items as $vs) :?>
                                        <option data-visibility='<?php echo $vs['visibility']?>' value="<?php echo $vs['id'];?>" 
                                        <?php echo (isset($where['category_id']) && $where['category_id']==$vs['id']) ? 'selected' : '' ?>>
                                             <?php echo str_repeat("&nbsp;&nbsp;&nbsp;&nbsp;",$vs['level']);?>
                                                 <?php echo $vs['name'].($vs['visibility'] == 'Hidden' ? '(隐藏)' : '');?>
                                                
                                              </option>
                                            <?php endforeach;?>
                                </select>
                                	</div>
							  	</div>
                                
                                <div class="control-group">
								<label class="control-label" for=template_id>模板</label>
								<div class="controls" id="ajaxtemplate">
								<?php 
                                	echo \Phalcon\Tag::selectStatic(array(
                                			"template_id[]",
                                			array(),//Template::find("status= 'Enabled' AND site_id='{$site_id}'"),
                                			"using" => array("id", "name"),
                                			"value"=>'',
											"id"=>'template_id',
											"multiple"=>'multiple',
											"data-rel"=>'chosen'
                                	));
                                	
                                	?>
                                	</div>
							  	</div>
							  	<div class="controls">
                                <?php echo \Phalcon\Tag::submitButton(array("确定",'class'=>'btn btn-small btn-primary','id'=>'submit')) ?>
                                <button type="reset" id="reset" class="btn btn-small">重置</button>
								</div>
						</fieldset>
						<?php echo \Phalcon\Tag::endForm()?>
						<div id="loading" class="loading">
						
						
						</div>
						
					            
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
			
			<script>
			$(document).ready(function(){
				loadtable();
				$('#submit').click(function(){

					var visibility =  $("#category_id").find("option:selected").attr('data-visibility');
					if(visibility=='Hidden'){
						
						$('#myModal>.modal-body>p').html('该分类处于隐藏状态,无法关联模板。');
			        	$('#myModal').modal('show');
			        	return false;
					}
					
					
					var msg = '关联后立即生效,用户查看相关页面是会根据最新的模板进行展示?<br>【<a href="javascript:;" id="submit_ok">确定</a>】【<a href="javascript:;" id="submit_no">取消</a>】';
					$('#myModal>.modal-body>p').html(msg);
		        	$('#myModal').modal('show');
		        	return false;
				});
				$('#submit_ok').live('click',function(){
					var template_id = $('#template_id').val();
					var category_id = $('#category_id').val();
					if(!template_id){
						$('#myModal>.modal-body>p').html('模板不能为空');
						$('#myModal').modal('show');
						return false;
					}
					if(!category_id){
						$('#myModal>.modal-body>p').html('分类不能为空');
						$('#myModal').modal('show');
						return false;
					}
					$.ajax({
				        type: "POST",
				        url: '/template/category',
				        data: {'ajax':1,'template_id':template_id,'category_id':category_id},
				        async:false,
				        dataType: "json",
				        success: function(data){
				        	$('#myModal>.modal-body>p').html(data.msg);
				        	$('#myModal').modal('show');
				        	loadtable();
				        	//$(".search-choice-close").trigger("click");
				        	$("#category_id").trigger("change");
				    	}
				    });
					setTimeout("$('#myModal').modal('hide')",600);
					return false;
				});

				$('#category_id').live('change',function(){
					var template_id = $('#template_id').val();
					var category_id = $('#category_id').val();

					//var visibility =  $("#category_id").find("option:selected").attr('data-visibility');
					//if(visibility=='Hidden'){
			        	//return ;
					//}
					
					$.ajax({
				        type: "POST",
				        url: '/template/ajaxtemplate',
				        data: {'ajax':1,'template_id':template_id,'category_id':category_id,'relation':0},
				        async:false,
				        success: function(data){
					        $('#ajaxtemplate').html(data);
				    	}
				    });
				});
				$('#reset').click(function(){
					$("#category_id").trigger("change");
				});
				
				//$('#clear_cache').live('click',function(){
				//	var template_id = $('#template_id').val();
				//	var category_id = $('#category_id').val();
				//	$.ajax({
				     //   type: "POST",
				     //   url: '/template/purge',
				    //    data: {'ajax':1,'template_id':template_id,'category_id':category_id,'relation':0},
				    //    async:false,
				    //    dataType:'json',
				     //   success: function(data){
					 //       $('#clear_cache_list').html(data.msg);
					 //       
					 //       setTimeout("$('#myModal').modal('hide')",600);
				    //	}
				  //  });
				//});
				
				$('#submit_no').live('click',function(){
					$('#myModal').modal('hide');
					$(".search-choice-close").trigger("click");
				});
			});
			function loadtable(){
				$.ajax({
			        type: "GET",
			        url: '/template/categorylist/1/1000/1',
			        data: {},
			        async:false,
			        success: function(data){
			        	$('#loading').html(data);
			    	}
			    });
			}
				
			</script>
