<!DOCTYPE html>
<html lang="en">
<head>

	<!-- start: Meta -->
	<?php if(isset($times) && isset($url)):?>
	<meta http-equiv="refresh" content="<?php echo $times;?>;url=<?php echo $url;?>">
	<?php endif;?>
	<meta charset="utf-8" />
	<title>Email Direct Marketing Platform</title>
	<meta name="description" content="Bootstrap Metro Dashboard" />
	<meta name="author" content="Dennis Ji" />
	<meta name="keyword" content="Metro, Metro UI, Dashboard, Bootstrap, Admin, Template, Theme, Responsive, Fluid, Retina" />
	<!-- end: Meta -->

	<!-- start: Mobile Specific -->
	<meta name="viewport" content="width=device-width, initial-scale=1" />
	<!-- end: Mobile Specific -->

	<!-- start: CSS -->
	<link id="bootstrap-style" href="/css/bootstrap.min.css" rel="stylesheet" />
	<link href="/css/bootstrap-responsive.min.css" rel="stylesheet" />
	<link id="base-style" href="/css/style.css" rel="stylesheet" />
	<link id="base-style-responsive" href="/css/style-responsive.css" rel="stylesheet" />
	<link href='/css/google/googleapis.css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800&subset=latin,cyrillic-ext,latin-ext' rel='stylesheet' type='text/css' />
	<link href='/css/editor/default.css' rel="stylesheet" type='text/css' />

	<!-- end: CSS -->


	<!-- The HTML5 shim, for IE6-8 support of HTML5 elements -->
	<!--[if lt IE 9]>
	  	<script src="/js/html5.js"></script>
		<link id="ie-style" href="/css/ie.css" rel="stylesheet" />
	<![endif]-->

	<!--[if IE 9]>
		<link id="ie9style" href="/css/ie9.css" rel="stylesheet" />
	<![endif]-->

	<!-- start: Favicon -->
	<link rel="shortcut icon" href="img/favicon.ico" />
	<!-- end: Favicon -->

	<!-- start: editor -->
	<script type="text/javascript" src="/js/kindeditor-min.js"></script>
	<script type="text/javascript" src="/js/lang/zh_CN.js"></script>
	<!-- end: editor -->

	<script src="/js/jquery-1.9.1.min.js"></script>
        <script src="/js/ajaxfileupload.js"></script>
</head>

<body>
		<!-- start: Header -->

	<div class="navbar">
		<div class="navbar-inner">
			<div class="container-fluid">
				<a class="btn btn-navbar" data-toggle="collapse" data-target=".top-nav.nav-collapse,.sidebar-nav.nav-collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>
				<a class="brand" href="/"><span>Email Direct Marketing Platform</span></a>

				<!-- start: Header Menu -->
				<div class="nav-no-collapse header-nav">
					<ul class="nav pull-right">
<!--						<li class="dropdown hidden-phone">
							<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
								<i class="halflings-icon white warning-sign"></i>
							</a>
							<ul class="dropdown-menu notifications">
								<li class="dropdown-menu-title">
 									<span>You have 11 notifications</span>
									<a href="#refresh"><i class="icon-repeat"></i></a>
								</li>
                            	<li>
                                    <a href="#">
										<span class="icon blue"><i class="icon-user"></i></span>
										<span class="message">New user registration</span>
										<span class="time">1 min</span>
                                    </a>
                                </li>
								<li>
                                    <a href="#">
										<span class="icon green"><i class="icon-comment-alt"></i></span>
										<span class="message">New comment</span>
										<span class="time">7 min</span>
                                    </a>
                                </li>
								<li>
                                    <a href="#">
										<span class="icon green"><i class="icon-comment-alt"></i></span>
										<span class="message">New comment</span>
										<span class="time">8 min</span>
                                    </a>
                                </li>
								<li>
                                    <a href="#">
										<span class="icon green"><i class="icon-comment-alt"></i></span>
										<span class="message">New comment</span>
										<span class="time">16 min</span>
                                    </a>
                                </li>
								<li>
                                    <a href="#">
										<span class="icon blue"><i class="icon-user"></i></span>
										<span class="message">New user registration</span>
										<span class="time">36 min</span>
                                    </a>
                                </li>
								<li>
                                    <a href="#">
										<span class="icon yellow"><i class="icon-shopping-cart"></i></span>
										<span class="message">2 items sold</span>
										<span class="time">1 hour</span>
                                    </a>
                                </li>
								<li class="warning">
                                    <a href="#">
										<span class="icon red"><i class="icon-user"></i></span>
										<span class="message">User deleted account</span>
										<span class="time">2 hour</span>
                                    </a>
                                </li>
								<li class="warning">
                                    <a href="#">
										<span class="icon red"><i class="icon-shopping-cart"></i></span>
										<span class="message">New comment</span>
										<span class="time">6 hour</span>
                                    </a>
                                </li>
								<li>
                                    <a href="#">
										<span class="icon green"><i class="icon-comment-alt"></i></span>
										<span class="message">New comment</span>
										<span class="time">yesterday</span>
                                    </a>
                                </li>
								<li>
                                    <a href="#">
										<span class="icon blue"><i class="icon-user"></i></span>
										<span class="message">New user registration</span>
										<span class="time">yesterday</span>
                                    </a>
                                </li>
                                <li class="dropdown-menu-sub-footer">
                            		<a>View all notifications</a>
								</li>
							</ul>
						</li>
						 start: Notifications Dropdown
						<li class="dropdown hidden-phone">
							<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
								<i class="halflings-icon white tasks"></i>
							</a>
							<ul class="dropdown-menu tasks">
								<li class="dropdown-menu-title">
 									<span>You have 17 tasks in progress</span>
									<a href="#refresh"><i class="icon-repeat"></i></a>
								</li>
								<li>
                                    <a href="#">
										<span class="header">
											<span class="title">iOS Development</span>
											<span class="percent"></span>
										</span>
                                        <div class="taskProgress progressSlim red">80</div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
										<span class="header">
											<span class="title">Android Development</span>
											<span class="percent"></span>
										</span>
                                        <div class="taskProgress progressSlim green">47</div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
										<span class="header">
											<span class="title">ARM Development</span>
											<span class="percent"></span>
										</span>
                                        <div class="taskProgress progressSlim yellow">32</div>
                                    </a>
                                </li>
								<li>
                                    <a href="#">
										<span class="header">
											<span class="title">ARM Development</span>
											<span class="percent"></span>
										</span>
                                        <div class="taskProgress progressSlim greenLight">63</div>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
										<span class="header">
											<span class="title">ARM Development</span>
											<span class="percent"></span>
										</span>
                                        <div class="taskProgress progressSlim orange">80</div>
                                    </a>
                                </li>
								<li>
                            		<a class="dropdown-menu-sub-footer">View all tasks</a>
								</li>
							</ul>
						</li>
						 end: Notifications Dropdown
						 start: Message Dropdown
						<li class="dropdown hidden-phone">
							<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
								<i class="halflings-icon white envelope"></i>
							</a>
							<ul class="dropdown-menu messages">
								<li class="dropdown-menu-title">
 									<span>You have 9 messages</span>
									<a href="#refresh"><i class="icon-repeat"></i></a>
								</li>
                            	<li>
                                    <a href="#">
										<span class="avatar"><img src="img/avatar.jpg" alt="Avatar"></span>
										<span class="header">
											<span class="from">
										    	Dennis Ji
										     </span>
											<span class="time">
										    	6 min
										    </span>
										</span>
                                        <span class="message">
                                            Lorem ipsum dolor sit amet consectetur adipiscing elit, et al commore
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
										<span class="avatar"><img src="img/avatar.jpg" alt="Avatar"></span>
										<span class="header">
											<span class="from">
										    	Dennis Ji
										     </span>
											<span class="time">
										    	56 min
										    </span>
										</span>
                                        <span class="message">
                                            Lorem ipsum dolor sit amet consectetur adipiscing elit, et al commore
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
										<span class="avatar"><img src="img/avatar.jpg" alt="Avatar"></span>
										<span class="header">
											<span class="from">
										    	Dennis Ji
										     </span>
											<span class="time">
										    	3 hours
										    </span>
										</span>
                                        <span class="message">
                                            Lorem ipsum dolor sit amet consectetur adipiscing elit, et al commore
                                        </span>
                                    </a>
                                </li>
								<li>
                                    <a href="#">
										<span class="avatar"><img src="img/avatar.jpg" alt="Avatar"></span>
										<span class="header">
											<span class="from">
										    	Dennis Ji
										     </span>
											<span class="time">
										    	yesterday
										    </span>
										</span>
                                        <span class="message">
                                            Lorem ipsum dolor sit amet consectetur adipiscing elit, et al commore
                                        </span>
                                    </a>
                                </li>
                                <li>
                                    <a href="#">
										<span class="avatar"><img src="img/avatar.jpg" alt="Avatar"></span>
										<span class="header">
											<span class="from">
										    	Dennis Ji
										     </span>
											<span class="time">
										    	Jul 25, 2012
										    </span>
										</span>
                                        <span class="message">
                                            Lorem ipsum dolor sit amet consectetur adipiscing elit, et al commore
                                        </span>
                                    </a>
                                </li>
								<li>
                            		<a class="dropdown-menu-sub-footer">View all messages</a>
								</li>
							</ul>
						</li>
						 end: Message Dropdown
						<li>
							<a class="btn" href="#">
								<i class="halflings-icon white wrench"></i>
							</a>
						</li>
						 start: User Dropdown -->
						<li class="dropdown">
<!--							<a class="btn dropdown-toggle" data-toggle="dropdown" href="#">
								<i class="halflings-icon white user"></i> Dennis Ji
								<span class="caret"></span>
							</a>-->
							<!--<ul class="dropdown-menu">-->
                                                            <?php if(!$this->session->has("auth")){?>
								<li><a href="/login/index"><i class="halflings-icon user"></i> Login/Logout</a></li>
                                                            <?php }else{?>
								<li><a href="/login/end"><i class="halflings-icon off"></i> Logout</a></li>
                                                            <?php }?>
							<!--</ul>-->
						</li>
						<!-- end: User Dropdown -->
					</ul>
				</div>
				<!-- end: Header Menu -->

			</div>
		</div>
	</div>

	<!-- start: Header -->
<?php if($this->session->has("auth")){?>
		<div class="container-fluid-full" style="">
		<div class="row-fluid">

			<!-- start: Main Menu -->
			<div id="sidebar-left" class="span2">
				<div class="nav-collapse sidebar-nav">
					<ul class="nav nav-tabs nav-stacked main-menu">
						<li><a href="/dashboard"><i class="icon-bar-chart"></i><strong class="hidden-tablet"> Dashboard</strong></a></li>
						<li>
							<a class="dropmenu" href="#"><i class="icon-folder-open"></i><strong class="hidden-tablet"> 分组管理</strong></a>
							<ul>
								<li><a class="submenu" href="/group/index"><i class="icon-list-alt"></i><span class="hidden-tablet"> 分组列表</span></a></li>
								<li><a class="submenu" href="/group/add"><i class="icon-edit"></i><span class="hidden-tablet"> 添加分组</span></a></li>
                                                                <li><a class="submenu" href="#"><i class="icon-edit"></i><span class="hidden-tablet"> 分组转换</span></a></li>
								<!--
								<li><a class="submenu" href="/template/edit"><i class="icon-edit"></i><span class="hidden-tablet"> 模板预览</span></a></li>
								 -->
							</ul>
						</li>
                                                <li>
							<a class="dropmenu" href="#"><i class="icon-folder-open"></i><strong class="hidden-tablet"> 联系人管理</strong></a>
							<ul>
								<li><a class="submenu" href="/contact/upload"><i class="icon-list-alt"></i><span class="hidden-tablet"> 导入联系人</span></a></li>
								<li><a class="submenu" href="/contact/index"><i class="icon-edit"></i><span class="hidden-tablet"> 联系人列表</span></a></li>

								<li><a class="submenu" href="/contact/add"><i class="icon-edit"></i><span class="hidden-tablet"> 添加联系人</span></a></li>

							</ul>
						</li>
						<!--
						<li><a href="tasks.html"><i class="icon-tasks"></i><span class="hidden-tablet"> Tasks</span></a></li>
						<li><a href="ui.html"><i class="icon-eye-open"></i><span class="hidden-tablet"> UI Features</span></a></li>
						<li><a href="widgets.html"><i class="icon-dashboard"></i><span class="hidden-tablet"> Widgets</span></a></li>
						<li>
							<a class="dropmenu" href="#"><i class="icon-folder-close-alt"></i><span class="hidden-tablet"> Dropdown</span><span class="label label-important"> 3 </span></a>
							<ul>
								<li><a class="submenu" href="submenu.html"><i class="icon-file-alt"></i><span class="hidden-tablet"> Sub Menu 1</span></a></li>
								<li><a class="submenu" href="submenu2.html"><i class="icon-file-alt"></i><span class="hidden-tablet"> Sub Menu 2</span></a></li>
								<li><a class="submenu" href="submenu3.html"><i class="icon-file-alt"></i><span class="hidden-tablet"> Sub Menu 3</span></a></li>
							</ul>
						</li>
						<li><a href="form.html"><i class="icon-edit"></i><span class="hidden-tablet"> Forms</span></a></li>
						<li><a href="chart.html"><i class="icon-list-alt"></i><span class="hidden-tablet"> Charts</span></a></li>
						<li><a href="typography.html"><i class="icon-font"></i><span class="hidden-tablet"> Typography</span></a></li>
						<li><a href="gallery.html"><i class="icon-picture"></i><span class="hidden-tablet"> Gallery</span></a></li>
						-->
						<li>
							<a class="dropmenu" href="#"><i class="icon-folder-open"></i><strong class="hidden-tablet"> 模板管理</strong></a>
							<ul>
								<li><a class="submenu" href="/template/index"><i class="icon-list-alt"></i><span class="hidden-tablet"> 模板列表</span></a></li>
								<li><a class="submenu" href="/template/edit"><i class="icon-edit"></i><span class="hidden-tablet"> 新增模板</span></a></li>
								<!--<li><a class="submenu" href="/template/category"><i class="icon-edit"></i><span class="hidden-tablet"> 分类模板关联 </span></a></li>-->
							</ul>
						</li>
                                                <li>
							<a class="dropmenu" href="#"><i class="icon-folder-close-alt"></i><strong class="hidden-tablet"> 内容管理</strong></a>
							<ul>
								<li><a class="submenu" href="/message"><i class="icon-align-justify"></i><span class="hidden-tablet"> 内容列表</span></a></li>
								<li><a class="submenu" href="/message/create"><i class="icon-edit"></i><span class="hidden-tablet"> 新增内容</span></a></li>
								<!--<li><a class="submenu" href="/message/move"><i class="icon-edit"></i><span class="hidden-tablet">文章分类迁移</span></a></li>-->
								<!--
								<li><a class="submenu" href="/article/move"><i class="icon-edit"></i><span class="hidden-tablet">集团文章分类迁移</span></a></li>
								 -->
							</ul>
						</li>

						<li>
							<a class="dropmenu" href="#"><i class="icon-folder-open"></i><strong class="hidden-tablet"> 任务管理</strong></a>
							<ul>
								<li><a class="submenu" href="/task/index"><i class="icon-list-alt"></i><span class="hidden-tablet"> 任务列表</span></a></li>
								<li><a class="submenu" href="/task/add"><i class="icon-edit"></i><span class="hidden-tablet"> 新增任务</span></a></li>
                                                                <li><a class="submenu" href="/queue/index"><i class="icon-edit"></i><span class="hidden-tablet"> 发送日志</span></a></li>
                                                                <li><a class="submenu" href="/task/upload"><i class="icon-edit"></i><span class="hidden-tablet"> 导入任务</span></a></li>
							</ul>
						</li>



<!--                                                <li>
							<a class="dropmenu" href="#"><i class="icon-folder-open"></i><strong class="hidden-tablet"> 图片管理</strong></a>
							<ul>
								<li><a class="submenu" href="/album/add"><i class="icon-edit"></i><span class="hidden-tablet"> 创建文件夹</span></a></li>
								<li><a class="submenu" href="/album/folder"><i class="icon-list-alt"></i><span class="hidden-tablet"> 浏览图片</span></a></li>
								<li><a class="submenu" href="/album/upload"><i class="icon-list-alt"></i><span class="hidden-tablet"> 上传图片</span></a></li>
							</ul>
						</li>-->

<!--						<li><a href="/template/preview"><i class="icon-file-alt"></i><strong class="hidden-tablet">页面预览 </strong></a></li>
						<li><a href="/template/purge"><i class="icon-calendar"></i><strong class="hidden-tablet"> 缓存管理 </strong></a></li>-->
						<!--

						<li><a href="file-manager.html"><i class="icon-folder-open"></i><span class="hidden-tablet"> File Manager</span></a></li>
						<li><a href="icon.html"><i class="icon-star"></i><span class="hidden-tablet"> Icons</span></a></li>
						<li><a href="login.html"><i class="icon-lock"></i><span class="hidden-tablet"> Login Page</span></a></li>
						-->
					</ul>
				</div>
			</div>
			<!-- end: Main Menu -->

			<noscript>
				<div class="alert alert-block span10">
					<h4 class="alert-heading">Warning!</h4>
					<p>You need to have <a href="http://en.wikipedia.org/wiki/JavaScript" target="_blank">JavaScript</a> enabled to use this site.</p>
				</div>
			</noscript>
			 <?php }?>
			<!-- start: Content -->
			<div id="content" class="span10">
                            


			<?php echo $this->getContent(); ?>

		</div><!--/#content.span10-->

		</div><!--/fluid-row-->


	<div class="modal hide fade" id="myModal">
		<div class="modal-header">
			<button type="button" class="close" data-dismiss="modal">×</button>
			<h3>提示信息</h3>
		</div>
		<div class="modal-body">
			<p></p>
		</div>
		<div class="modal-footer">
			<a href="#" class="btn" data-dismiss="modal">关闭</a>
		</div>
	</div>

	<div class="modal hide fade" id="successModal">
		<div class="modal-header">
			<button type="button" class="close success" data-dismiss="modal">×</button>
			<h3>提示信息</h3>
		</div>
		<div class="modal-body">
			<p></p>
		</div>
		<div class="modal-footer">
			<a href="#" class="btn success" data-dismiss="modal">确定</a>
		</div>
	</div>

	<div class="clearfix"></div>

	<footer>

		<!--p>
			<span style="text-align:left;float:left">&copy; 2013 <a href="http://jiji262.github.io/Bootstrap_Metro_Dashboard/" alt="Bootstrap_Metro_Dashboard">Bootstrap Metro Dashboard</a></span>

		</p-->

	</footer>

	<!-- start: JavaScript-->

	<script src="/js/jquery-migrate-1.0.0.min.js"></script>

		<script src="/js/jquery-ui-1.10.0.custom.min.js"></script>

		<script src="/js/jquery.ui.touch-punch.js"></script>

		<script src="/js/modernizr.js"></script>

		<script src="/js/bootstrap.min.js"></script>

		<script src="/js/jquery.cookie.js"></script>

		<script src='/js/fullcalendar.min.js'></script>
	<!-- 暂时不使用js分页效果 -->
		<!--script src='/js/jquery.dataTables.min.js'></script-->

		<script src="/js/excanvas.js"></script>
	<script src="/js/jquery.flot.js"></script>
	<script src="/js/jquery.flot.pie.js"></script>
	<script src="/js/jquery.flot.stack.js"></script>
	<script src="/js/jquery.flot.resize.min.js"></script>

		<script src="/js/jquery.chosen.min.js"></script>

		<script src="/js/jquery.uniform.min.js"></script>

		<!--script src="/js/jquery.cleditor.min.js"></script-->

		<script src="/js/jquery.noty.js"></script>

		<script src="/js/jquery.elfinder.min.js"></script>

		<script src="/js/jquery.raty.min.js"></script>

		<script src="/js/jquery.iphone.toggle.js"></script>

		<script src="/js/jquery.uploadify-3.1.min.js"></script>

		<script src="/js/jquery.gritter.min.js"></script>

		<script src="/js/jquery.imagesloaded.js"></script>

		<script src="/js/jquery.masonry.min.js"></script>

		<script src="/js/jquery.knob.modified.js"></script>

		<script src="/js/jquery.sparkline.min.js"></script>

		<script src="/js/My97DatePicker/WdatePicker.js"></script>

		<script src="/js/counter.js"></script>

		<script src="/js/retina.js"></script>

		<script src="/js/custom.js"></script>
	<!-- end: JavaScript-->

</body>
</html>
