<script type="text/javascript">


</script>
<div class="row-fluid sortable">		
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon user"></i><span class="break"></span><?php ?></h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
            </div>
        </div>
        
        <div class="box-content">
            <div class="row-fluid">
                <div class="">
                        <div class="" id="">
                                <label></label>
                                <form name="form" action="/queue/list" method="post">
                                任务：
                                <select name="task_id" id="task_id" style="width:auto;">
                                        <option value="">全部</option>
                                        <?php foreach($taskId as $v):?>
                                        <option value="<?php echo $v->id;?>"<?php if(isset($where['task_id']) && $where['task_id']==$v->id):?> selected="selected"<?php endif;?>><?php echo $v->name;?></option>
                                        <?php endforeach;?>
                                </select>
                                <input id="submit" type="submit" value="查询" class="btn btn-primary btn-search" />
                                </form>
                        </div>
                </div>
        </div>
            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr>
                        
                        <th>任务</th>
                        <th>发送到</th>
                        <th>队列状态</th>
                        <th>加入时间</th>
                        <th>完成时间</th>
                    </tr>
                </thead>   
                <tbody>
                    <?php
//                    $task_arr = $this->objToArray->ohYeah($datas);
                    foreach ($page->items as $vs) {
                        ?>
                        <tr>
                           
                            <td ><?php echo $vs->tname;?></td>
                            <td><?php echo $vs->name; ?></td>
                            <td><?php echo $vs->status; ?></td>
                            <td><?php echo $vs->ctime; ?></td>
                            <td><?php echo $vs->mtime; ?></td>

                        </tr>
<?php } ?>

                </tbody>
            </table>   
            <div class="row-fluid">
                    <div class="span12 center">
                            <div class="dataTables_paginate paging_bootstrap pagination">
                                    <span class="page_text">共有 <?php echo $page->total_items;?> 条记录, 每页显示 <?php echo $page->pageSize;?> 条, 当前<?php echo $page->current;?>/<?php echo $page->total_pages;?> 页:</span>
                                    <ul> 
                                            <li class="prev"><a href="/queue/list">首页</a></li>
                                            <li class="prev"><a href="/queue/list/<?php echo $page->before;?>/<?php echo $page->pageSize;?>">← 上一页</a></li>
                                            <li class="next"><a href="/queue/list/<?php echo $page->next;?>/<?php echo $page->pageSize;?>">下一页 → </a></li>
                                            <li class=""><a href="/queue/list/<?php echo $page->last;?>/<?php echo $page->pageSize;?>">尾页</a></li>
                                    </ul>


                                  <?php echo \Phalcon\Tag::selectStatic(array("pagesize", array('10'=>'10','25' => '25', '50' => '50','100'=>'100'),'class'=>'span1',"value"=>$page->pageSize , "onchange"=>"location.href='/queue/list/1/'+this.value;"));?>


                            </div>
                    </div>
            </div>
        </div>
    </div><!--/span-->

</div><!--/row-->
<script language="javascript" type="text/javascript">
    $(function(){
        $("#language").change(function(){
            var language = $(this).children('option:selected').val();
            $('.datatable tbody tr').hide();
            $('.datatable tbody tr[language="'+language+'"]').show();
//            $.post('index',{language:language},function(data){
//                if(!data.status){
//            },'json');
        });

      });
</script>





