<!--<style type="text/css">  
   .alert alert-danger{color:#a94442;background-color:#f2dede;border-color:#ebccd1}
 </style> -->
			<div class="row-fluid sortable">
				<div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="halflings-icon edit"></i><span class="break"></span>添加任务</h2>
						<div class="box-icon">
							<a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
							<a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
							<a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
						</div>
					</div>
                                    <!--<div class="alert alert-danger"></div>-->
					<div class="box-content">
                                            <form class="form-horizontal" method="post" id="category_post" action="/work/addHandle">
							<fieldset>
                                                            
                                                          <div class="control-group">
								<label class="control-label" for="focusedInput">任务名称</label>
								<div class="controls">
                                                                    <input class="input-xlarge focused" id="name" name="name" type="text" value="">
								</div>
							  </div>
                                                            
                                                          <div class="control-group">
								<label class="control-label" for="selectError3">发送类型</label>
								<div class="controls">
                                                                    <select id="type" name="type">
                                                                        
                                                                                <option value="SMS">SMS</option>
                                                                                <option value="Email" selected="selected">Email</option>
                                                                        
								  </select>
								</div>
							  </div>
                                                            
                                                          <div class="control-group">
								<label class="control-label" for="selectError3">发送分组</label>
								<div class="controls">
                                                                    <select id="group_id" name="group_id">
                                                                                <option value="">全部</option>
                                                                        <?php foreach($group_ids as $val){?>
                                                                                <option value="<?php echo $val->id;?>"><?php echo $val->name;?></option>
                                                                        <?php }?>
								  </select>
								</div>
							  </div>
                                                            
                                                        <div class="control-group">
								<label class="control-label" for="selectError3">发送模板</label>
								<div class="controls">
                                                                    <select id="template_id" name="template_id">
                                                                                <option value="">请选择</option>
                                                                        <?php foreach($init_template_ids as $val){?>
                                                                                <option value="<?php echo $val->id;?>"><?php echo $val->name;?></option>
                                                                        <?php }?>
								  </select>
                                                                    
                                                                  
								</div>
							  </div>
                                                            
                                                          <div class="control-group">
								<label class="control-label" for="selectError3">发送内容</label>
								<div class="controls">
                                                                    <select id="message_id" name="message_id">
                                                                                <option value="">请选择</option>
                                                                        <?php foreach($init_message_ids as $val){?>
                                                                                <option value="<?php echo $val->id;?>"><?php echo $val->title;?></option>
                                                                        <?php }?>
								  </select>
                                                                    
                                                                  
								</div>
							  </div>
                                                            
<!--                                                          <div class="control-group">
								<label class="control-label" for="selectError3">状态</label>
								<div class="controls">
                                                                    <select id="status" name="status">
                                                                                <option value="New">New</option>
                                                                                <option value="Processing">Processing</option>
                                                                                <option value="Completed">Completed</option>
                                                                                <option value="Failed">Failed</option>
								  </select>
								</div>
							  </div>-->

							  <div class="form-actions">
                                                              <button id="preview" type="button" class="btn btn-success">预览</button>
                                                              <button id="submit" type="button" class="btn btn-primary">添加</button>
                                                              <button class="btn" type="submit" id="setoff" name="setoff" value="setoff">取消</button>
							  </div>
							</fieldset>
						  </form>
					
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
<script language="javascript" type="text/javascript">
    

$(function(){
    $("#type").change(function(){
        $("#template_id").empty();
        $("#message_id").empty();
        var type = $(this).children('option:selected').val();
        $.post('getIds',{type:type},function(data){
            for(var s in data.message_ids)
                $("#message_id").append("<option value='"+data.message_ids[s].id+"'>"+data.message_ids[s].title+"</option>");
            for(var s in data.template_ids)
                $("#template_id").append("<option value='"+data.template_ids[s].id+"'>"+data.template_ids[s].name+"</option>");
            if(!data.status){
            }
        },'json');
    });
    $("#submit").click(function(){
        var name = $('#name').val();
        var type = $("#type").val();
        var group_id = $("#group_id").val();
        var message_id = $("#message_id").val();
        var template_id = $("#template_id").val();
        if(!name){
                $('#myModal>.modal-body>p').html('分组名称不能为空');
                $('#myModal').modal('show');
                return false;
        }
        if ($.trim(name) == "") {
             $('#myModal>.modal-body>p').html('分组名称不能为空格');
             $('#myModal').modal('show');
            return false;
        }
        if(name.length > 50){
            $('#myModal>.modal-body>p').html('分组名称长度不能超过50');
            $('#myModal').modal('show');
            return false;
        }
        if(!template_id){
                $('#myModal>.modal-body>p').html('请选择模板ID');
                $('#myModal').modal('show');
                return false;
        }
        if(!message_id){
                $('#myModal>.modal-body>p').html('请选择内容ID');
                $('#myModal').modal('show');
                return false;
        }
        
//        var setoff = $("#setoff").val();
        var name = $("#name").val();
        $.post('/task/addHandle',{name:name,type:type,group_id:group_id,message_id:message_id,template_id:template_id},function(data){
            $('#myModal>.modal-body>p').html(data.msg);
            $('#myModal').modal('show');
            if(!data.status){
//                    $('#myModal>.modal-body>p').append('<p><span id="jumpsec">5</span>秒后跳转到 <a  href="/category/index">列表页面</a>，<a id="nojump" href="javascript:;">取消</a></p>');
//                    window.template_jump = setInterval('jumpsec()',1000);
                    window.template_jump = setInterval("location.href='/task/index'",600);
            }
        },'json');
    });
    $("#preview").click(function(){
        var message_id = $("#message_id").val();
        var template_id = $("#template_id").val();
        if(!template_id){
                $('#myModal>.modal-body>p').html('请选择模板ID');
                $('#myModal').modal('show');
                return false;
        }
        if(!message_id){
                $('#myModal>.modal-body>p').html('请选择内容ID');
                $('#myModal').modal('show');
                return false;
        }
        window.open('/preview/email/'+message_id+'/'+template_id);
    });
    
    $('#nojump').live('click',function(){
            if(window.template_jump){
                     clearInterval(window.template_jump);
                     $('#myModal').modal('hide');
            }
            return false;
    });
});
function jumpsec(){
    var sec = $('#jumpsec').html();
    sec = parseInt(sec);
    if(sec>1){
            sec = sec-1;
            $('#jumpsec').html(sec);
    }else{
            location.href='/group/index';
    }
}

$("#parent_id").change(function(){
   var id = $(this).children('option:selected').val();
   $.post('getLang',{id:id},function(data){
        
        $("#hd_language").val(data.data['language']);
        $("#language").val(data.data['language']).attr("disabled", "true");
       
//       if(data.data['parent_id'] === null){
//            $("#hd_language").val(data.data['language']);
//            $("#language").val(data.data['language']).removeAttr("disabled");
//       }
       
       if( id === 'NULL'){
           $("#language").val(data.data['language']).removeAttr("disabled");
       }
       
   },'json');
});
</script>		
                       
