<?php 

// print_r($site); 
$items = $site;
?>
<script type="text/javascript">


</script>
<div class="row-fluid sortable">		
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon user"></i><span class="break"></span><?php ?></h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
            </div>
        </div>
        
        <div class="box-content">
            <div class="row-fluid">
							<div class="">
								<div class="" id="" style="float:left">
									<label></label>
									<form name="form1" action="/category/list" method="post">
									
						
									
									
									<!--<input id="submit" type="submit" value="查询" class="btn btn-primary btn-search" />-->
									</form>
								</div>
                                <div style="float:right"><a href="/category/add"><input  type="button" value="添加分类" class="btn btn-primary btn-search" /></a></div>
							</div>
						</div>
            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr>
                        <th>名称</th>
                        <th>描述</th>
                        <th>用户</th>
                        <th>密码</th>
                        <th>操作</th>
                    </tr>
                </thead>   
                <tbody>
                    <?php
                    // $cates_arr = $this->objToArray->ohYeah($pages);
                    // $items = $this->tree->_tree($cates_arr, $parent_id = 0, $level = 0);
                    foreach ($items as $item) {
                        // print_r($item);
                        ?>
                        <tr>
                        <td><?php echo $item->name ?></td>
                            <td><?php echo $item->description ?></td>
                           <td><?php echo $item->username ?></td>
                            <td><?php echo $item->password ?></td>
                            
                        
                            <td class="center">
                                <a title="查看分类" class="btn btn-success" href="/category/show/<?php echo $item->id;?>">
                                    <i class="halflings-icon white zoom-in"></i>  
                                </a>
                                <a title="编辑分类" class="btn btn-info" href="/category/edit/<?php echo $item->id;?>">
                                    <i class="halflings-icon white edit"></i>  
                                </a>
                                <a title="添加分类" class="btn btn-success" href="/category/add/<?php echo $item->id;?>">
                                    <i class="halflings-icon plus white zoom-in"></i>  
                                </a>
                               
                            </td>
                        </tr>
<?php } ?>

                </tbody>
            </table>   
            
        </div>
    </div><!--/span-->

</div><!--/row-->
<script language="javascript" type="text/javascript">
    $(function(){
        $("#language").change(function(){
            var language = $(this).children('option:selected').val();
            $('.datatable tbody tr').hide();
            $('.datatable tbody tr[language="'+language+'"]').show();
//            $.post('index',{language:language},function(data){
//                if(!data.status){
//            },'json');
        });

      });
</script>