
			<div class="row-fluid sortable">
				<div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="halflings-icon edit"></i><span class="break"></span>编辑分类</h2>
						<div class="box-icon">
							<a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
							<a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
							<a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
						</div>
					</div>
					<div class="box-content">
                                            <form class="form-horizontal" method="post" action="/group/editHandle">
							<fieldset>
                                                            <input type="hidden" id="id" name="id" value="<?php echo $group->id;?>" />
                                                          <div class="control-group">
								<label class="control-label" for="focusedInput">分组名称</label>
								<div class="controls">
                                                                    <input class="input-xlarge focused" id="name" name="name" type="text" value="<?php echo $group->name;?>">
								</div>
							  </div>
                                                  
                                                    
                                                          <div class="control-group">
								<label class="control-label" for="selectError3">分组描述</label>
								<div class="controls">
                                                                    <textarea id="description" name="description"><?php echo $group->description;?></textarea>
								</div>
							  </div>
							  
							  <div class="form-actions">
                                                              <button id="submit" type="button" class="btn btn-primary">修改</button>
								<button class="btn" type="submit" id="setoff" name="setoff" value="setoff">取消</button>
							  </div>
							</fieldset>
						  </form>
					
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
<script language="javascript" type="text/javascript">
    

$(function(){
    $("#submit").click(function(){
        var name = $('#name').val();
        if(!name){
                $('#myModal>.modal-body>p').html('分组名称不能为空');
                $('#myModal').modal('show');
                return false;
        }
        if ($.trim(name) == "") {
             $('#myModal>.modal-body>p').html('分组名称不能为空格');
             $('#myModal').modal('show');
            return false;
        }
        if(name.length > 10){
            $('#myModal>.modal-body>p').html('分组名称长度不能超过10');
            $('#myModal').modal('show');
            return false;
        }
        var id = $("#id").val();
        var name = $("#name").val();
        var description = $("#description").val();
        $.post('/group/editHandle',{id:id,name:name,description:description},function(data){
            
                $('#myModal>.modal-body>p').html(data.msg);
                $('#myModal').modal('show');
                if(!data.status){
//                    location.href='/category/index';
//                    return false;
//                        $('#myModal>.modal-body>p').append(data.msg);
                        
                        window.template_jump = setInterval("location.href='/group/index'",600);
                }
            },'json');
        });
        $('#nojump').live('click',function(){
                if(window.template_jump){
                         clearInterval(window.template_jump);
                         $('#myModal').modal('hide');
                }
                return false;
        });
    });
    function jumpsec(){
        var sec = $('#jumpsec').html();
        sec = parseInt(sec);
        if(sec>1){
                sec = sec-1;
                $('#jumpsec').html(sec);
        }else{
                location.href='/group/index';
        }
    }


</script>				

