<script type="text/javascript">


</script>
<div class="row-fluid sortable">		
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon user"></i><span class="break"></span><?php ?></h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
            </div>
        </div>
        
        <div class="box-content">
            <div class="row-fluid">
							<div class="">
								
                                                            <div style="float:left"><a href="/group/add"><input  type="button" value="添加分组" class="btn btn-primary btn-search" /></a></div>
							</div>
						</div>
            <table class="table table-striped table-bordered bootstrap-datatable datatable">
                <thead>
                    <tr>
                        
                        <th>分组名称</th>
                        <th>分组描述</th>
                        <th>创建时间</th>
                    </tr>
                </thead>   
                <tbody>
                    <?php
                    $group_arr = $this->objToArray->ohYeah($group);
                    foreach ($group_arr as $vs) {
                        ?>
                        <tr>
                           
                            <td ><?php echo $vs['name']?></td>
                            <td><?php echo $vs['description']; ?></td>
                            
                            <td><?php echo $vs['ctime']; ?></td>
                            <td class="center">
<!--                                <a title="查看分类" class="btn btn-success" href="/category/show/<?php echo $vs['id'];?>">
                                    <i class="halflings-icon white zoom-in"></i>  
                                </a>-->
                                <a title="编辑分类" class="btn btn-info" href="/group/edit/<?php echo $vs['id'];?>">
                                    <i class="halflings-icon white edit"></i>  
                                </a>
<!--                                <a title="添加分类" class="btn btn-success" href="/group/add/<?php echo $vs['id'];?>">
                                    <i class="halflings-icon plus white zoom-in"></i>  
                                </a>-->
                               
                            </td>
                        </tr>
<?php } ?>

                </tbody>
            </table>   
            
        </div>
    </div><!--/span-->

</div><!--/row-->
<script language="javascript" type="text/javascript">
    $(function(){
        $("#language").change(function(){
            var language = $(this).children('option:selected').val();
            $('.datatable tbody tr').hide();
            $('.datatable tbody tr[language="'+language+'"]').show();
//            $.post('index',{language:language},function(data){
//                if(!data.status){
//            },'json');
        });

      });
</script>





