
			<div class="row-fluid sortable">
				<div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="halflings-icon edit"></i><span class="break"></span>查看分类</h2>
						<div class="box-icon">
							<a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
							<a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
							<a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
						</div>
					</div>
					<div class="box-content">
                                            <form class="form-horizontal" method="post" action="#">
							<fieldset>
							  <div class="control-group">
								<label class="control-label" for="focusedInput">分类名称</label>
								<div class="controls">
                                                                    <input class="input-xlarge focused" id="focusedInput" name="name" type="text" readonly="readonly" value="<?php echo $cates->name;?>">
								</div>
							  </div>
<!--							  <div class="control-group">
								<label class="control-label">Uneditable input</label>
								<div class="controls">
								  <span class="input-xlarge uneditable-input">Some value here</span>
								</div>
							  </div>
							  <div class="control-group">
								<label class="control-label" for="disabledInput">Disabled input</label>
								<div class="controls">
								  <input class="input-xlarge disabled" id="disabledInput" type="text" placeholder="Disabled input here…" disabled="">
								</div>
							  </div>
							  <div class="control-group">
								<label class="control-label" for="optionsCheckbox2">Disabled checkbox</label>
								<div class="controls">
								  <label class="checkbox">
									<input type="checkbox" id="optionsCheckbox2" value="option1" disabled="">
									This is a disabled checkbox
								  </label>
								</div>
							  </div>
							  <div class="control-group warning">
								<label class="control-label" for="inputWarning">Input with warning</label>
								<div class="controls">
								  <input type="text" id="inputWarning">
								  <span class="help-inline">Something may have gone wrong</span>
								</div>
							  </div>
							  <div class="control-group error">
								<label class="control-label" for="inputError">Input with error</label>
								<div class="controls">
								  <input type="text" id="inputError">
								  <span class="help-inline">Please correct the error</span>
								</div>
							  </div>
							  <div class="control-group success">
								<label class="control-label" for="inputSuccess">Input with success</label>
								<div class="controls">
								  <input type="text" id="inputSuccess">
								  <span class="help-inline">Woohoo!</span>
								</div>
							  </div>-->
<!--							  <div class="control-group">
								<label class="control-label" for="selectError3">上级分类</label>
								<div class="controls">
                                                                    <select id="selectError3" name="parent_id">
                                                                        <?php 
                                                                                $cates_arr = $this->objToArray->ohYeah($pages);
                                                                                $items = $this->tree->_tree($cates_arr, $parent_id = 0, $level = 0);
                                                                                foreach ($items as $vs){?>
                                                                                <option value="<?php echo $vs['id'];?>">
                                                                                    <?php echo str_repeat("&nbsp;&nbsp;&nbsp;&nbsp;",$vs['level']);?>
                                                                                    <?php echo $vs['name'];?>
                                                                                </option>
                                                                        <?php }?>
								  </select>
								</div>
							  </div>-->
                                                          <div class="control-group">
								<label class="control-label" for="selectError3">语言</label>
								<div class="controls">
                                                                    <input class="input-xlarge focused" id="focusedInput" name="name" type="text" readonly="readonly" value="<?php  if($cates->language == 'cn'){
                                                                        echo '简体';
                                                                    }elseif($cates->language == 'tw'){
                                                                        echo '繁体';
                                                                    }else{
                                                                        echo '英语';
                                                                    }?>">
								</div>
							  </div>
                                                          <div class="control-group">
								<label class="control-label" for="selectError3">可见性</label>
								<div class="controls">
                                                                    <input class="input-xlarge focused" id="focusedInput" name="name" type="text" readonly="readonly" value="<?php echo ($cates->visibility == 'Visible' ? '显示' : '隐藏');?>">
								</div>
							  </div>
                                                          <div class="control-group">
								<label class="control-label" for="selectError3">分类描述</label>
								<div class="controls">
                                                                    <textarea name="description" readonly="readonly"><?php echo $cates->description; ?></textarea>
								</div>
							  </div>
                                                          <div class="control-group">
								<a href="/category/index"><label class="control-label" for="selectError3"><button id="submit" type="button" class="btn btn-primary">返回</button></label></a>
							  </div>
<!--							  <div class="control-group">
								<label class="control-label" for="selectError">Modern Select</label>
								<div class="controls">
								  <select id="selectError" data-rel="chosen">
									<option>Option 1</option>
									<option>Option 2</option>
									<option>Option 3</option>
									<option>Option 4</option>
									<option>Option 5</option>
								  </select>
								</div>
							  </div>
							  <div class="control-group">
								<label class="control-label" for="selectError1">Multiple Select / Tags</label>
								<div class="controls">
								  <select id="selectError1" multiple data-rel="chosen">
									<option>Option 1</option>
									<option selected>Option 2</option>
									<option>Option 3</option>
									<option>Option 4</option>
									<option>Option 5</option>
								  </select>
								</div>
							  </div>
							  <div class="control-group">
								<label class="control-label" for="selectError2">Group Select</label>
								<div class="controls">
									<select data-placeholder="Your Favorite Football Team" id="selectError2" data-rel="chosen">
										<option value=""></option>
										<optgroup label="NFC EAST">
										  <option>Dallas Cowboys</option>
										  <option>New York Giants</option>
										  <option>Philadelphia Eagles</option>
										  <option>Washington Redskins</option>
										</optgroup>
										<optgroup label="NFC NORTH">
										  <option>Chicago Bears</option>
										  <option>Detroit Lions</option>
										  <option>Green Bay Packers</option>
										  <option>Minnesota Vikings</option>
										</optgroup>
										<optgroup label="NFC SOUTH">
										  <option>Atlanta Falcons</option>
										  <option>Carolina Panthers</option>
										  <option>New Orleans Saints</option>
										  <option>Tampa Bay Buccaneers</option>
										</optgroup>
										<optgroup label="NFC WEST">
										  <option>Arizona Cardinals</option>
										  <option>St. Louis Rams</option>
										  <option>San Francisco 49ers</option>
										  <option>Seattle Seahawks</option>
										</optgroup>
										<optgroup label="AFC EAST">
										  <option>Buffalo Dennis Jis</option>
										  <option>Miami Dolphins</option>
										  <option>New England Patriots</option>
										  <option>New York Jets</option>
										</optgroup>
										<optgroup label="AFC NORTH">
										  <option>Baltimore Ravens</option>
										  <option>Cincinnati Bengals</option>
										  <option>Cleveland Browns</option>
										  <option>Pittsburgh Steelers</option>
										</optgroup>
										<optgroup label="AFC SOUTH">
										  <option>Houston Texans</option>
										  <option>Indianapolis Colts</option>
										  <option>Jacksonville Jaguars</option>
										  <option>Tennessee Titans</option>
										</optgroup>
										<optgroup label="AFC WEST">
										  <option>Denver Broncos</option>
										  <option>Kansas City Chiefs</option>
										  <option>Oakland Raiders</option>
										  <option>San Diego Chargers</option>
										</optgroup>
								  </select>
								</div>
							  </div>-->
<!--							  <div class="form-actions">
								<button type="submit" class="btn btn-primary">添加</button>
								<button class="btn">取消</button>
							  </div>-->
							</fieldset>
						  </form>
					
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
			

