			<ul class="breadcrumb">
				<li>
					<i class="icon-home"></i>
					<a href="/">Home</a> 
					<i class="icon-angle-right"></i>
				</li>
				<li><a href="#">文章列表</a></li>
			</ul>

			<div class="row-fluid sortable">		
				<div class="box span12">
					<div class="box-header" data-original-title>
						<h2><i class="halflings-icon align-justify"></i><span class="break"></span>文章列表</h2>
						<div class="box-icon">
							<a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
							<a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
							<a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
						</div>
					</div>
					<div class="box-content">
						<div class="row-fluid">
							<div class="">
								<div class="" id="">
									<label></label>
									<form name="form1" action="/article/list" method="post">
									<!--标题: <input type="text" name="title" id="title" value="<?php echo isset($where['title'])?$where['title']:'';?>">
									语言：
									<select name="language" id="language" style="width:auto;">
										<option value="">全部</option>
										<option value="cn"<?php if(isset($where['language']) && $where['language']=='cn'):?> selected="selected"<?php endif;?>>CN</option>
										<option value="tw"<?php if(isset($where['language']) && $where['language']=='tw'):?> selected="selected"<?php endif;?>>TW</option>
										<option value="en"<?php if(isset($where['language']) && $where['language']=='en'):?> selected="selected"<?php endif;?>>EN</option>
									</select>
									事业部-->分类：
									<select name="division_category_id" id="division_category_id" style="width:auto;">
									  	<option value="">全部</option>
										<?php
					                    $cates_arr = $this->objToArray->ohYeah($divisionCategory);
					                    $items = $this->tree->_tree($cates_arr, $parent_id = 0, $level = 0);
					                    foreach ($items as $vs) :
					                        ?>
										<option value="<?php echo $vs['id'];?>"<?php if(isset($where['division_category_id']) && $where['division_category_id']==$vs['id']):?> selected="selected"<?php endif;?>>
										<?php echo str_repeat("&nbsp;&nbsp;&nbsp;&nbsp;", $vs['level']); ?>
	    								<?php echo $vs['name']; ?>
	    								</option>
										<?php endforeach;?>
									</select>
									语言：
									<select name="language" id="language" style="width:auto;">
										<option value="">全部</option>
										<?php foreach($language as $k => $v):?>
										<option value="<?php echo $k;?>"<?php if(isset($where['language']) && $where['language']==$k):?> selected="selected"<?php endif;?>><?php echo $v;?></option>
										<?php endforeach;?>
									</select>
									可见性：
									<select name="visibility" id="visibility" style="width:auto;">
										<option value="">全部</option>
										<option value="Visible"<?php if(isset($where['visibility']) && $where['visibility']=='Visible'):?> selected="selected"<?php endif;?>>显示</option>	
										<option value="Hidden"<?php if(isset($where['visibility']) && $where['visibility']=='Hidden'):?> selected="selected"<?php endif;?>>隐藏</option>		
									</select>
									<!--分享：
									<select name="share" id="share" style="width:auto;">
										<option value="">全部</option>
										<option value="Y"<?php if(isset($where['share']) && $where['share']=='Y'):?> selected="selected"<?php endif;?>>是</option>	
										<option value="N"<?php if(isset($where['share']) && $where['share']=='N'):?> selected="selected"<?php endif;?>>否</option>		
									</select>-->
									开始时间：<input type="text" name="bctime" id="bctime" value="<?php echo isset($where['bctime'])?$where['bctime']:'';?>" style="width:80px;" onclick="WdatePicker({maxDate:'#F{$dp.$D(\'ectime\')}'})" />
									结束时间：<input type="text" name="ectime" id="ectime" value="<?php echo isset($where['ectime'])?$where['ectime']:'';?>" style="width:80px;" onclick="WdatePicker({minDate:'#F{$dp.$D(\'bctime\')}'})" />
									<input id="submit" type="submit" value="查询" class="btn btn-primary btn-search" />
									<input id="btnAdd" type="button" value="添加文章" class="btn btn-primary btn-search" />
									</form>
								</div>
							</div>
						</div>
						<div class="row-fluid">
							<div class="">
								<div class="" id="" style="border:1px solid #eee;margin:5px 0;">
									<span style="display:inline-block;padding:5px;">
										批量操作：
										<input id="btnShow" type="button" value="显示" class="btn btn-primary btn-search" url="/article/delete" />
										<input id="btnHidden" type="button" value="隐藏" class="btn btn-primary btn-search" url="/article/delete" />
										<input id="btnDelete" type="button" value="删除" class="btn btn-primary btn-search" url="/article/delete" />
									</span>
								</div>
							</div>
						</div>
						<table class="table table-striped table-bordered bootstrap-datatable datatable">
						  <thead>
							  <tr>
							  	  <th width="10"><input type="checkbox" name="ckall" /></th>
								  <th>标题</th>
								  <th>所属分类</th>
								  <th>作者</th>
								  <th>语言</th>
								  <th>分享</th>
								  <th>可见性</th>
								  <th>添加时间</th>
								  <th>操作</th>
							  </tr>
						  </thead>   
						  <tbody>
						  <?php foreach ($page->items as $item):?>
							<tr>
								<td><input type="checkbox" name="id" value="<?php echo $item->id;?>" /></td>
								<td><?php echo $item->title;?></td>
								<td class="center"><?php echo $item->category->name;?></td>
								<td class="center"><?php echo $item->author;?></td>
								<td><?php echo $language[$item->language];?></td>
								<td><?php echo $item->share=='N'?'<span class="label label-error">否</span>':'<span class="label label-success">是</span>';?></td>
								<td class="center">
									<?php echo $item->visibility=='Visible'?'<span class="label label-success">显示</span>':'<span class="label label-error">隐藏</span>';?>
								</td>
								<td><?php echo $item->ctime;?></td>
								<td class="center">
									<!--a class="btn btn-success" href="#">
										<i class="halflings-icon white zoom-in"></i>  
									</a-->
									<a title="编辑文章" class="btn btn-info" href="/article/edit/<?php echo $item->id;?>">
										<i class="halflings-icon white edit"></i>  
									</a>
									<!--a class="btn btn-danger" href="#">
										<i class="halflings-icon white trash"></i> 
									</a-->
								</td>
							</tr>
							<?php endforeach;?>
						</tbody>
					  </table> 
					  <div class="row-fluid">
						  <div class="span12 center">
							  <div class="dataTables_paginate paging_bootstrap pagination">
						  	  	  <span class="page_text">共有 <?php echo $page->total_items;?> 条记录, 每页显示 <?php echo $page->pageSize;?> 条, 当前<?php echo $page->current;?>/<?php echo ($page->total_pages==0?1:$page->total_pages);?> 页:</span>
								  <ul>
								  	  <li class="prev"><a href="/article/list">首页</a></li>
									  <li class="prev"><a href="/article/list/<?php echo $page->before;?>/<?php echo $page->pageSize;?>">上一页</a></li>
									  <li class="next"><a href="/article/list/<?php echo $page->next;?>/<?php echo $page->pageSize;?>">下一页</a></li>
									  <li class=""><a href="/article/list/<?php echo $page->last;?>/<?php echo $page->pageSize;?>">尾页</a></li>
								  </ul>
								  <span class="page_text">每页行数:</span>
								  <select name="pagesize" style="width:auto;" class="pagesize" onchange="location.href='/article/list/1/'+this.value;">
									<option value="10"<?php if($page->pageSize==10):?> selected="selected"<?php endif;?>>10</option>
									<option value="25"<?php if($page->pageSize==25):?> selected="selected"<?php endif;?>>25</option>
									<option value="50"<?php if($page->pageSize==50):?> selected="selected"<?php endif;?>>50</option>
									<option value="100"<?php if($page->pageSize==100):?> selected="selected"<?php endif;?>>100</option>
								</select> 
								<span class="page_text"> 条</span>
							  </div>
						  </div>
					  </div>           
					</div>
				</div><!--/span-->
			
			</div><!--/row-->
