<script type="text/javascript">


</script>
<div class="row-fluid sortable">		
    <div class="box span12">
        <div class="box-header" data-original-title>
            <h2><i class="halflings-icon user"></i><span class="break"></span><?php ?></h2>
            <div class="box-icon">
                <a href="#" class="btn-setting"><i class="halflings-icon wrench"></i></a>
                <a href="#" class="btn-minimize"><i class="halflings-icon chevron-up"></i></a>
                <a href="#" class="btn-close"><i class="halflings-icon remove"></i></a>
            </div>
        </div>
        
        <div class="box-content">
            <div class="row-fluid">
							<div class="">
								<div class="" id="" style="float:left">
									<a href="/album/upload"><input  type="button" value="上传图片" class="btn btn-primary btn-search" /></a>
								</div>
							</div>
						</div>
           
            
            <table class="table table-striped table-bordered bootstrap-datatable datatable" style="margin-top: 30px;">  
                
                <div style="margin-top: 20px;">  
                    
                        <?php 
//                        
//                    header('Content-type: image/png;');    
                    $pictures_arr = $this->objToArray->ohYeah($image);
                    
                    foreach($pictures_arr as $vs){
                    ?>
                    <div style="float: left;width: 200px;margin-left: 22px;margin-top: 22px;">
						<a href="/image/raw/<?php echo $folder;?>/<?php echo $vs['file']['filename'];?>">
							<img src="/image/thumbnail/<?php echo $folder;?>/<?php echo $vs['file']['filename'];?>" />
						</a>
					</div>
                    <?php }?>
                   
                </div>
            </table>
            
            <div class="row-fluid">
                    <div class="span12 center">
                            <div class="dataTables_paginate paging_bootstrap pagination">
                                
                                    <span class="page_text">共有 <?php  echo $count;?> 条记录, 每页显示 3 条, 当前<?php echo $skip==0?1:$skip;?>/<?php echo (ceil($count / 3)==0?1:ceil($count / 3));?> 页:</span>
                                    <?php 
            $mongo_page = new mongoPage($count,3,$folder,$skip);
            $pageshow = $mongo_page->showpage();
            ?>              
                                    <ul>
                                        <?php echo $pageshow;?>
                                    </ul>

                            </div>
                    </div>
            </div> 
            
        </div>
    </div><!--/span-->

</div><!--/row-->
<script language="javascript" type="text/javascript">
   
</script>

<?php
	class mongoPage {
  		private $total;    	//总记录
  		private $pagesize;  	//每页显示多少条
  		private $limit;   		//limit
  		private $page;   		//当前页码
  		private $pagenum; 		//总页码
  		private $url;    		//地址
  		private $bothnum; 		//两边保持数字分页的量
        private $folder;
  
  	//构造方法初始化
  	public function __construct($_total, $_pagesize,$folder,$page) {
   		$this->total = $_total ? $_total : 1;
   		$this->pagesize = $_pagesize;
  		$this->pagenum = ceil($this->total / $this->pagesize);
   		$this->page = $page;
   		$this->limit = "LIMIT ".($this->page-1)*$this->pagesize.",$this->pagesize";
   		$this->url = $this->setUrl();
   		$this->bothnum = 2;
                $this->folder = $folder;
  	}
  
  	//拦截器
  	public function __get($_key) {
   		return $this->$_key;
  	}
  
  	//获取当前页码
  	private function setPage() {
   		if (!empty($_GET['page'])) {
    			if ($_GET['page'] > 0) {
     				if ($_GET['page'] > $this->pagenum) {
      					return $this->pagenum;
     				} else {
      					return $_GET['page'];
     				}
    			} else {
     				return 1;
    			}
   		} else {
    			return 1;
   		}
  	} 
  
  	//获取地址
  	private function setUrl() {
   		$_url = $_SERVER["REQUEST_URI"];
   		$_par = parse_url($_url);
   		if (isset($_par['query'])) {
    			parse_str($_par['query'],$_query);
    			unset($_query['page']);
    			$_url = $_par['path'].'?'.http_build_query($_query);
   		}
   		return $_url;
  	}  	//数字目录
  	private function pageList() {
   		for ($i=$this->bothnum;$i>=1;$i--) {
    		$_page = $this->page-$i;
    		if ($_page < 1) continue;
    			$_pagelist .= ' <a href="/album/browse/'.$this->folder.'/'.$_page.'">'.$_page.'</a> ';
   		}
   		$_pagelist .= ' <span class="me">'.$this->page.'</span> ';
   		for ($i=1;$i<=$this->bothnum;$i++) {
   	 		$_page = $this->page+$i;
    			if ($_page > $this->pagenum) break;
    			$_pagelist .= ' <a href="/album/browse/'.$this->folder.'/'.$_page.'">'.$_page.'</a> ';
   		}
   		return $_pagelist;
  	}
  
  	//首页
  	private function first() {
//   		if ($this->page > $this->bothnum+1) {
    			return ' <li class="prev"><a href="/album/browse/'.$this->folder.'">首页</a></li>';
//   		}
  	}
  
  	//上一页
  	private function prev() {
   		if ($this->page == 1) {
    			return '<li class="prev"><span class="disabled">上一页</span></li>';
                }elseif($this->page == 0){
                    return ' <li class="prev"><a href="/album/browse/'.$this->folder.'">上一页</a></li> ';
                }else{
                    return ' <li class="prev"><a href="/album/browse/'.$this->folder.'/'.($this->page-1).'">上一页</a></li> ';
                }
   		
  	}
  
  	//下一页
  	private function next() {
   		if ($this->page == $this->pagenum) {
    			return '<li class="prev"><span class="disabled">下一页</span></li>';
   		}
                if($this->page == 0){
                    return ' <li class="prev"><a href="/album/browse/'.$this->folder.'/'.($this->page+2).'">下一页</a></li> ';
                }else{
                    return ' <li class="prev"><a href="/album/browse/'.$this->folder.'/'.($this->page+1).'">下一页</a></li> ';
                }
  	}
  
  	//尾页
  	private function last() {
//   		if ($this->pagenum - $this->page > $this->bothnum) {
    			return '<li class="prev"><a href="/album/browse/'.$this->folder.'/'.$this->pagenum.'">尾页</a> </li>';
//   		}
  	}
  
  	//分页信息
  	public function showpage() {
		$_page = null;
   		$_page .= $this->first();
//   		$_page .= $this->pageList();
   		
   		$_page .= $this->prev();
   		$_page .= $this->next();
                $_page .= $this->last();
   		return $_page;
  	}
 }
?>



